### ISSUE TITLE
appfy.recipe.gae:sdk Always makes HTTP request even if the part is not built

### ISSUE THREAD

**Issue by Trii** [prmtl/appfy.recipe.gae#17]
It looks like the initialization calls `self.find_latest_sdk_url()` if url is not set regardless of the part being built. If I try to build a single part `./bin/buildout install nosetests` I get the following info in my console

```
Josh@kapbook:appengine-buildout-template$ ./bin/buildout install nosetests
gae_sdk: Using SDK version found at https://www.googleapis.com/download/storage/v1/b/appengine-sdks/o/featured%2Fgoogle_appengine_1.9.17.zip?generation=1418060609606000&alt=media
Updating nosetests.
```

**Comment by prmtl** [comment]
Thanks for the fix!
New version (0.9.10) has been released.
